<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:include href="./Delegates.xslt"/>
  <xsl:include href="./New.xslt"/>
  <xsl:include href="./GetEntities.xslt"/>
  <xsl:include href="./Changes.xslt"/>
  <xsl:include href="./Filter.xslt"/>
  <xsl:include href="./Fill.xslt"/>
  <xsl:include href="./Insert.xslt"/>
  <xsl:include href="./Update.xslt"/>
  <xsl:include href="./Delete.xslt"/>
</xsl:stylesheet>