DROP USER northwind CASCADE;
DROP TABLESPACE NORTHWIND INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE SMALLFILE TABLESPACE NORTHWIND
	DATAFILE 
		'C:\oracle\oradata\NORTHWIND\DATAFILE\NORTHWIND.dat' SIZE 500M AUTOEXTEND ON,
	EXTENT MANAGEMENT LOCAL AUTOALLOCATE
	SEGMENT SPACE MANAGEMENT AUTO
	ONLINE;

CREATE USER northwind IDENTIFIED BY oracle DEFAULT TABLESPACE NORTHWIND TEMPORARY TABLESPACE TEMP PROFILE DEFAULT QUOTA UNLIMITED ON NORTHWIND;
GRANT DBA, CONNECT, RESOURCE TO northwind;
GRANT CREATE SESSION TO northwind;
